//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YogaRetreatAPI.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YogaRetreatEntities : DbContext
    {
        public YogaRetreatEntities()
            : base("name=YogaRetreatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HomeOwner> HomeOwners { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Member> Members { get; set; }
    }
}
